if(EXISTS "C:/Users/semas/OneDrive/Desktop/Z_/cen429_sema_sahin_elif_ak_cpp/build_win/src/tests/travelexpensetracker/travelexpensetracker_tests[1]_tests.cmake")
  include("C:/Users/semas/OneDrive/Desktop/Z_/cen429_sema_sahin_elif_ak_cpp/build_win/src/tests/travelexpensetracker/travelexpensetracker_tests[1]_tests.cmake")
else()
  add_test(travelexpensetracker_tests_NOT_BUILT travelexpensetracker_tests_NOT_BUILT)
endif()
